prefix = "vm"
resource_group_name = "RG-Playground-Y001"
location = "eastus"
domain_name_label = "predmo"
mysql_server_name = "servermmsql"
sql_administrator_login = "sqladmin"
sql_administrator_login_password = "P@ssw0rd1234"
public_network_access_enabled = false
admin_username = "myadmin"
admin_password = "Password1234!"
wordpress_image = "wordpress"   // There seem to be an issue with php-fpm image of wordpress that's why I'm using wordpress image
